apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: boarding-week2
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default

  selector:
    matchLabels:
      app: boarding-week2

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
