replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

nodeSelector:
  workload: monitoring

tolerations:
  - key: workload
    operator: Equal
    value: monitoring
    effect: NoSchedule

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: false
