server:
  persistentVolume:
    enabled: false

  retention: 1d

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi

  nodeSelector:
    workload: monitoring

  tolerations:
    - key: workload
      operator: Equal
      value: monitoring
      effect: NoSchedule

alertmanager:
  enabled: false

pushgateway:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false


serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: "boarding-week2"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "boarding-week2.default.svc.cluster.local:8000"
